Addressed most comments from reviews
TODO in YAMLs:
- check the /etc/openvswitch mounts on line 684 of managed/multizone/ovnkube-node

RBAC & ROLES:
- have a new role for cluster manager, with only the basics permissions it needs

TODO: read the configmap before rendering...

Signed-off-by: Riccardo Ravaioli <rravaiol@redhat.com>

diff --git a/bindata/network/ovn-kubernetes/managed/multi-zone-interconnect/ovnkube-node.yaml b/bindata/network/ovn-kubernetes/managed/multi-zone-interconnect/ovnkube-node.yaml
--- a/bindata/network/ovn-kubernetes/managed/multi-zone-interconnect/ovnkube-node.yaml
+++ b/bindata/network/ovn-kubernetes/managed/multi-zone-interconnect/ovnkube-node.yaml
@@ -1,6 +1,13 @@
 kind: DaemonSet
 apiVersion: apps/v1
 metadata:
+  {{ if eq .OVN_NODE_MODE "dpu-host" }}
+  name: ovnkube-node-dpu-host
+  {{ else if eq .OVN_NODE_MODE "smart-nic" }}
+  name: ovnkube-node-smart-nic
+  {{ else }}
+  name: ovnkube-node
+  {{ end }}
   name: ovnkube-node
   namespace: openshift-ovn-kubernetes
   annotations:
@@ -10,7 +17,13 @@ metadata:
 spec:
   selector:
     matchLabels:
+      {{ if eq .OVN_NODE_MODE "dpu-host" }}
+      app: ovnkube-node-dpu-host
+      {{ else if eq .OVN_NODE_MODE "smart-nic" }}
+      app: ovnkube-node-smart-nic
+      {{ else }}
       app: ovnkube-node
+      {{ end }}
   updateStrategy:
     type: RollingUpdate
     rollingUpdate:
@@ -20,26 +33,49 @@ spec:
       annotations:
         target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
       labels:
+        {{ if eq .OVN_NODE_MODE "dpu-host" }}
+        app: ovnkube-node-dpu-host
+        {{ else if eq .OVN_NODE_MODE "smart-nic" }}
+        app: ovnkube-node-smart-nic
+        {{ else }}
         app: ovnkube-node
+        {{ end }}
         component: network
         type: infra
         openshift.io/component: network
         kubernetes.io/os: "linux"
+        ovn-db-pod: "true"
     spec:
       affinity:
         nodeAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
             nodeSelectorTerms:
             - matchExpressions:
-              - key: network.operator.openshift.io/dpu-host
+              {{ if .DpuHostModeLabel }}
+              - key: {{ .DpuHostModeLabel }}
                 {{ if eq .OVN_NODE_MODE "dpu-host" }}
+                operator: Exists
+                {{ else if eq .OVN_NODE_MODE "smart-nic" }}
+                operator: DoesNotExist
+                {{ else }}
+                operator: DoesNotExist
+                {{ end }}
+              {{ end }}
+              {{ if .SmartNicModeLabel }}
+              - key: {{ .SmartNicModeLabel }}
+                {{ if eq .OVN_NODE_MODE "dpu-host" }}
+                operator: DoesNotExist
+                {{ else if eq .OVN_NODE_MODE "smart-nic" }}
                 operator: Exists
                 {{ else }}
                 operator: DoesNotExist
                 {{ end }}
-              - key: network.operator.openshift.io/dpu
+              {{ end }}
+              {{ if .DpuModeLabel }}
+              - key: {{ .DpuModeLabel }}
                 operator: DoesNotExist
-      serviceAccountName: ovn-kubernetes-controller
+              {{ end }}
+      serviceAccountName: ovn-kubernetes-node
       hostNetwork: true
       dnsPolicy: Default
       hostPID: true
@@ -51,7 +87,6 @@ spec:
       # /run/openvswitch -> tmpfs - ovsdb sockets
       # /env -> configmap env-overrides - debug overrides
       containers:
-      {{ if eq .OVN_NODE_MODE "full" }}
       # ovn-controller: programs the vswitch with flows from the sbdb
       - name: ovn-controller
         image: "{{.OvnImage}}"
@@ -150,7 +185,7 @@ spec:
 
             # Ensure total number of log files does not exceed the maximum configured from OVNPolicyAuditMaxLogFiles
             num_files=$(ls -1 ${LOGDIR}/acl-audit-log* 2>/dev/null | wc -l)
-            if [ "$num_files" -gt "MAXLOGFILES" ]; then
+            if [ "$num_files" -gt "$MAXLOGFILES" ]; then
               num_to_delete=$(( num_files - ${MAXLOGFILES} ))
               ls -1t ${LOGDIR}/acl-audit-log* 2>/dev/null | tail -$num_to_delete | xargs -I {} rm {}
             fi
@@ -168,7 +203,6 @@ spec:
           name: node-log
         - mountPath: /run/ovn/
           name: run-ovn
-      {{ end }}
       - name: kube-rbac-proxy-node
         image: {{.KubeRBACProxyImage}}
         command:
@@ -300,31 +334,30 @@ spec:
           echo "$(date -Iseconds) - starting ovn-northd"
           exec ovn-northd \
             --no-chdir "-vconsole:${OVN_LOG_LEVEL}" -vfile:off "-vPATTERN:console:{{.OVN_LOG_PATTERN_CONSOLE}}" \
-            --pidfile /var/run/ovn/ovn-northd.pid &
+            --pidfile /var/run/ovn/ovn-northd.pid \
+            --n-threads={{.NorthdThreads}} &
 
           wait $!
         lifecycle:
           preStop:
             exec:
               command:
-                - OVN_MANAGE_OVSDB=no
-                - /usr/share/ovn/scripts/ovn-ctl
-                - stop_northd
+                - /bin/bash
+                - -c
+                - OVN_MANAGE_OVSDB=no /usr/share/ovn/scripts/ovn-ctl stop_northd
         env:
         - name: OVN_LOG_LEVEL
           value: info
         volumeMounts:
-        - mountPath: /etc/openvswitch/
+        - mountPath: /etc/ovn
           name: etc-openvswitch
-        - mountPath: /var/lib/openvswitch/
-          name: var-lib-openvswitch
-        - mountPath: /run/openvswitch/
-          name: run-openvswitch
+        - mountPath: /var/log/ovn
+          name: node-log
         - mountPath: /run/ovn/
           name: run-ovn
         - mountPath: /env
           name: env-overrides
-        - mountPath: /ovn-cert # not needed, but useful when exec'ing in to pod.
+        - mountPath: /ovn-cert  # not needed, but useful when exec'ing in to pod.
           name: ovn-cert
         - mountPath: /ovn-ca
           name: ovn-ca
@@ -360,8 +393,6 @@ spec:
 
           bracketify() { case "$1" in *:*) echo "[$1]" ;; *) echo "$1" ;; esac }
 
-          # checks if a db pod is part of a current cluster
-
           OVN_ARGS="--no-monitor"
           exec /usr/share/ovn/scripts/ovn-ctl ${OVN_ARGS} \
             --ovn-nb-log="-vconsole:${OVN_LOG_LEVEL} -vfile:off -vPATTERN:console:{{.OVN_LOG_PATTERN_CONSOLE}}" \
@@ -381,6 +412,47 @@ spec:
                 #configure northd_probe_interval
                 OVN_NB_CTL="ovn-nbctl"
 
+                # retry an operation a number of times, sleeping 2 seconds between each try
+                retry() {
+                  local tries=${1}
+                  local desc=${2}
+                  local cmd=${3}
+
+                  local retries=0
+                  while ! ${cmd}; do
+                    (( retries += 1 ))
+                    if [[ "${retries}" -gt ${tries} ]]; then
+                      echo "$(date -Iseconds) - ERROR - nbdb ${desc} - too many failed attempts, giving up"
+                      return 1
+                    fi
+                    echo "$(date -Iseconds) - WARN - nbdb ${desc} - failed try ${retries}, retrying..."
+                    sleep 2
+                  done
+                  echo "$(date -Iseconds) - INFO - nbdb ${desc} - success"
+                  return 0
+                }
+
+                # set the connection and inactivity probe
+                if ! retry 60 "inactivity-probe" "ovn-nbctl --no-leader-only -t 5 set-connection pssl:{{.OVN_NB_PORT}}{{.LISTEN_DUAL_STACK}} -- set connection . inactivity_probe={{.OVN_NB_INACTIVITY_PROBE}}"; then
+                  exit 1
+                fi
+
+                # Upgrade the db if required.
+                DB_SCHEMA="/usr/share/ovn/ovn-nb.ovsschema"
+                DB_SERVER="unix:/var/run/ovn/ovnnb_db.sock"
+                schema_name=$(ovsdb-tool schema-name $DB_SCHEMA)
+                db_version=$(ovsdb-client -t 10 get-schema-version "$DB_SERVER" "$schema_name")
+                target_version=$(ovsdb-tool schema-version "$DB_SCHEMA")
+
+                if ovsdb-tool compare-versions "$db_version" == "$target_version"; then
+                  :
+                elif ovsdb-tool compare-versions "$db_version" ">" "$target_version"; then
+                    echo "Database $schema_name has newer schema version ($db_version) than our local schema ($target_version), possibly an upgrade is partially complete?"
+                else
+                    echo "Upgrading database $schema_name from schema version $db_version to $target_version"
+                    ovsdb-client -t 30 convert "$DB_SERVER" "$DB_SCHEMA"
+                fi
+
                 echo "Setting the IC zone to ${K8S_NODE}"
                 retries=0
                 current_probe_interval=0
@@ -395,7 +467,7 @@ spec:
                   fi
                 done
 
-                northd_probe_interval=${OVN_NORTHD_PROBE_INTERVAL:-5000}
+                northd_probe_interval=${OVN_NORTHD_PROBE_INTERVAL:-10000}
                 echo "Setting northd probe interval to ${northd_probe_interval} ms"
                 retries=0
                 current_probe_interval=0
@@ -425,17 +497,27 @@ spec:
                   done
                 fi
 
+                # Enable/disable IPsec
+                {{ if .OVNIPsecEnable }}
+                ipsec=true
+                {{ else }}
+                ipsec=false
+                {{ end }}
+                if ! retry 20 "ipsec" "${OVN_NB_CTL} set nb_global . ipsec=${ipsec}"; then
+                  exit 1
+                fi
           preStop:
             exec:
               command:
-                - /usr/bin/ovn-appctl
-                - -t
-                - /var/run/ovn/ovnnb_db.ctl
-                - exit
+                - /bin/bash
+                - -c
+                - |
+                  echo "$(date -Iseconds) - stopping nbdb"
+                  /usr/share/ovn/scripts/ovn-ctl stop_nb_ovsdb
+                  echo "$(date -Iseconds) - nbdb stopped"
+                  rm -f /var/run/ovn/ovnnb_db.pid
         readinessProbe:
-{{ if not .IsSNO }}
           initialDelaySeconds: 90
-{{ end }}
           timeoutSeconds: 5
           exec:
             command:
@@ -448,7 +530,8 @@ spec:
                 echo "NB DB is not running or active."
                 exit 1
               fi
-
+              # set trim-on-compaction
+              /usr/bin/ovn-appctl -t /var/run/ovn/ovnnb_db.ctl --timeout=5 ovsdb-server/memory-trim-on-compaction on 2>/dev/null
         env:
         - name: OVN_LOG_LEVEL
           value: info
@@ -459,19 +542,15 @@ spec:
             fieldRef:
               fieldPath: spec.nodeName
         volumeMounts:
-        - mountPath: /etc/openvswitch/
+        - mountPath: /etc/ovn
           name: etc-openvswitch
-        - mountPath: /etc/ovn/
-          name: etc-openvswitch
-        - mountPath: /var/lib/openvswitch/
-          name: var-lib-openvswitch
-        - mountPath: /run/openvswitch/
-          name: run-openvswitch
+        - mountPath: /var/log/ovn
+          name: node-log
         - mountPath: /run/ovn/
           name: run-ovn
         - mountPath: /env
           name: env-overrides
-        - mountPath: /ovn-cert
+        - mountPath: /ovn-cert  # not needed, but useful when exec'ing in to pod.
           name: ovn-cert
         - mountPath: /ovn-ca
           name: ovn-ca
@@ -481,7 +560,7 @@ spec:
             memory: 300Mi
         terminationMessagePolicy: FallbackToLogsOnError
 
-      # sbdb: the southbound, or logical network object DB. In standalone mode listening on unix socket
+      # sbdb: the southbound, or flow DB. In standalone mode listening on unix socket
       - name: sbdb
         image: "{{.OvnImage}}"
         command:
@@ -524,17 +603,64 @@ spec:
                 set -x
                 rm -f /var/run/ovn/ovnsb_db.pid
 
+                # retry an operation a number of times, sleeping 2 seconds between each try
+                retry() {
+                  local tries=${1}
+                  local desc=${2}
+                  local cmd=${3}
+
+                  local retries=0
+                  while ! ${cmd}; do
+                    (( retries += 1 ))
+                    if [[ "${retries}" -gt ${tries} ]]; then
+                      echo "$(date -Iseconds) - ERROR - sbdb ${desc} - too many failed attempts, giving up"
+                      return 1
+                    fi
+                    echo "$(date -Iseconds) - WARN - sbdb ${desc} - failed try ${retries}, retrying..."
+                    sleep 2
+                  done
+                  echo "$(date -Iseconds) - INFO - sbdb ${desc} - success"
+                  return 0
+                }
+
+                # set the connection and inactivity probe
+                if ! retry 60 "inactivity-probe" "ovn-sbctl --no-leader-only -t 5 set-connection pssl:{{.OVN_SB_PORT}}{{.LISTEN_DUAL_STACK}} -- set connection . inactivity_probe={{.OVN_CONTROLLER_INACTIVITY_PROBE}}"; then
+                  exit 1
+                fi
+
+                # Upgrade the db if required.
+                DB_SCHEMA="/usr/share/ovn/ovn-sb.ovsschema"
+                DB_SERVER="unix:/var/run/ovn/ovnsb_db.sock"
+                schema_name=$(ovsdb-tool schema-name $DB_SCHEMA)
+                db_version=$(ovsdb-client -t 10 get-schema-version "$DB_SERVER" "$schema_name")
+                target_version=$(ovsdb-tool schema-version "$DB_SCHEMA")
+
+                if ovsdb-tool compare-versions "$db_version" == "$target_version"; then
+                  :
+                elif ovsdb-tool compare-versions "$db_version" ">" "$target_version"; then
+                    echo "Database $schema_name has newer schema version ($db_version) than our local schema ($target_version), possibly an upgrade is partially complete?"
+                else
+                    echo "Upgrading database $schema_name from schema version $db_version to $target_version"
+                    ovsdb-client -t 30 convert "$DB_SERVER" "$DB_SCHEMA"
+                fi
+
+                # Kill some time while the cluster converges by checking IPsec status
+                OVN_SB_CTL="ovn-sbctl"
+                if ! retry 20 "ipsec" "${OVN_SB_CTL} get sb_global . ipsec"; then
+                  exit 1
+                fi
           preStop:
             exec:
               command:
-                - /usr/bin/ovn-appctl
-                - -t
-                - /var/run/ovn/ovnsb_db.ctl
-                - exit
+                - /bin/bash
+                - -c
+                - |
+                  echo "$(date -Iseconds) - stopping sbdb"
+                  /usr/share/ovn/scripts/ovn-ctl stop_sb_ovsdb
+                  echo "$(date -Iseconds) - sbdb stopped"
+                  rm -f /var/run/ovn/ovnsb_db.pid
         readinessProbe:
-{{ if not .IsSNO }}
           initialDelaySeconds: 90
-{{ end }}
           timeoutSeconds: 5
           exec:
             command:
@@ -547,34 +673,32 @@ spec:
                 echo "SB DB is not running or active."
                 exit 1
               fi
-
+              # set trim-on-compaction
+              /usr/bin/ovn-appctl -t /var/run/ovn/ovnsb_db.ctl --timeout=5 ovsdb-server/memory-trim-on-compaction on 2>/dev/null
         env:
         - name: OVN_LOG_LEVEL
           value: info
         volumeMounts:
-        - mountPath: /etc/openvswitch/
-          name: etc-openvswitch
         - mountPath: /etc/ovn/
           name: etc-openvswitch
-        - mountPath: /var/lib/openvswitch/
-          name: var-lib-openvswitch
-        - mountPath: /run/openvswitch/
-          name: run-openvswitch
         - mountPath: /run/ovn/
           name: run-ovn
         - mountPath: /env
           name: env-overrides
-        - mountPath: /ovn-cert
+        - mountPath: /ovn-cert  # not needed, but useful when exec'ing in to pod.
           name: ovn-cert
         - mountPath: /ovn-ca
           name: ovn-ca
+        - mountPath: /var/log/ovn
+          name: node-log
+
         resources:
           requests:
             cpu: 10m
             memory: 300Mi
         terminationMessagePolicy: FallbackToLogsOnError
 
-      - name: kube-rbac-proxy-ncm
+      - name: kube-rbac-proxy-controller
         image: {{.KubeRBACProxyImage}}
         command:
         - /bin/bash
@@ -695,7 +819,7 @@ spec:
           name: ovnkube-config
         - mountPath: /env
           name: env-overrides
-        - mountPath: /ovn-cert
+        - mountPath: /ovn-cert  # not needed, but useful when exec'ing in to pod.
           name: ovn-cert
         - mountPath: /ovn-ca
           name: ovn-ca
@@ -711,7 +835,7 @@ spec:
             fieldRef:
               fieldPath: spec.nodeName
         ports:
-        - name: metrics-port-c  # 15 characters max on windows
+        - name: metrics-port-c  # c stands for controller, we only have 15 characters max for ports on a windows platform
           containerPort: 29113
         terminationMessagePolicy: FallbackToLogsOnError
 
@@ -817,6 +941,9 @@ spec:
           if [[ -n "${OVNKUBE_NODE_MGMT_PORT_NETDEV}" ]] ; then
             node_mgmt_port_netdev_flags="--ovnkube-node-mgmt-port-netdev ${OVNKUBE_NODE_MGMT_PORT_NETDEV}"
           fi
+          if [[ -n "${OVNKUBE_NODE_MGMT_PORT_DP_RESOURCE_NAME}" ]] ; then
+            node_mgmt_port_netdev_flags="$node_mgmt_port_netdev_flags --ovnkube-node-mgmt-port-dp-resource-name ${OVNKUBE_NODE_MGMT_PORT_DP_RESOURCE_NAME}"
+          fi
 
           multi_network_enabled_flag=
           if [[ "{{.OVN_MULTI_NETWORK_ENABLE}}" == "true" ]]; then
@@ -883,6 +1010,10 @@ spec:
         - name: IPFIX_SAMPLING
           value: "{{.IPFIXSampling}}"
         {{ end }}
+        {{ if and (.MgmtPortResourceName) (or (eq .OVN_NODE_MODE "smart-nic") (eq .OVN_NODE_MODE "dpu-host")) }}
+        - name: OVNKUBE_NODE_MGMT_PORT_DP_RESOURCE_NAME
+          value: {{ .MgmtPortResourceName }}
+        {{ end }}
         - name: K8S_NODE
           valueFrom:
             fieldRef:
@@ -939,7 +1070,7 @@ spec:
           name: ovnkube-config
         - mountPath: /env
           name: env-overrides
-        - mountPath: /ovn-cert
+        - mountPath: /ovn-cert  # not needed, but useful when exec'ing in to pod.
           name: ovn-cert
         - mountPath: /ovn-ca
           name: ovn-ca
@@ -947,6 +1078,13 @@ spec:
           requests:
             cpu: 10m
             memory: 300Mi
+            {{ if and (.MgmtPortResourceName) (or (eq .OVN_NODE_MODE "smart-nic") (eq .OVN_NODE_MODE "dpu-host")) }}
+            {{ .MgmtPortResourceName }}: '1'
+            {{ end }}
+          {{ if and (.MgmtPortResourceName) (or (eq .OVN_NODE_MODE "smart-nic") (eq .OVN_NODE_MODE "dpu-host")) }}
+          limits:
+            {{ .MgmtPortResourceName }}: '1'
+          {{ end }}
         lifecycle:
           preStop:
             exec:
@@ -1043,18 +1181,18 @@ spec:
           path: /var/lib/openvswitch/data
       - name: etc-openvswitch
         hostPath:
-          path: /var/lib/ovn-ic/etc  # different path than 4.13 and single-zone 4.14
+          path: /var/lib/ovn-ic/etc  # different path than 4.13 and single-zone 4.14 to avoid collision during upgrade
       - name: run-openvswitch
         hostPath:
           path: /var/run/openvswitch
       - name: run-ovn
         hostPath:
-          path: /var/run/ovn-ic  # different path than 4.13 and single-zone 4.14
-      {{ if eq .OVN_NODE_MODE "full" }}
+          path: /var/run/ovn-ic  # different path than 4.13 and single-zone 4.14 to avoid collision during upgrade
+      {{ if or (eq .OVN_NODE_MODE "full") (eq .OVN_NODE_MODE "smart-nic") }}
       # Used for placement of ACL audit logs
       - name: node-log
         hostPath:
-          path: /var/log/ovn-ic  # different path than 4.13 and single-zone 4.14
+          path: /var/log/ovn
       - name: log-socket
         hostPath:
           path: /dev/log
diff --git a/bindata/network/ovn-kubernetes/self-hosted/multi-zone-interconnect/ovnkube-node.yaml b/bindata/network/ovn-kubernetes/self-hosted/multi-zone-interconnect/ovnkube-node.yaml
--- a/bindata/network/ovn-kubernetes/self-hosted/multi-zone-interconnect/ovnkube-node.yaml
+++ b/bindata/network/ovn-kubernetes/self-hosted/multi-zone-interconnect/ovnkube-node.yaml
@@ -1,7 +1,13 @@
 kind: DaemonSet
 apiVersion: apps/v1
 metadata:
+  {{ if eq .OVN_NODE_MODE "dpu-host" }}
+  name: ovnkube-node-dpu-host
+  {{ else if eq .OVN_NODE_MODE "smart-nic" }}
+  name: ovnkube-node-smart-nic
+  {{ else }}
   name: ovnkube-node
+  {{ end }}
   namespace: openshift-ovn-kubernetes
   annotations:
     kubernetes.io/description: |
@@ -10,7 +16,13 @@ metadata:
 spec:
   selector:
     matchLabels:
+      {{ if eq .OVN_NODE_MODE "dpu-host" }}
+      app: ovnkube-node-dpu-host
+      {{ else if eq .OVN_NODE_MODE "smart-nic" }}
+      app: ovnkube-node-smart-nic
+      {{ else }}
       app: ovnkube-node
+      {{ end }}
   updateStrategy:
     type: RollingUpdate
     rollingUpdate:
@@ -20,26 +32,49 @@ spec:
       annotations:
         target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
       labels:
+        {{ if eq .OVN_NODE_MODE "dpu-host" }}
+        app: ovnkube-node-dpu-host
+        {{ else if eq .OVN_NODE_MODE "smart-nic" }}
+        app: ovnkube-node-smart-nic
+        {{ else }}
         app: ovnkube-node
+        {{ end }}
         component: network
         type: infra
         openshift.io/component: network
         kubernetes.io/os: "linux"
+        ovn-db-pod: "true"
     spec:
       affinity:
         nodeAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
             nodeSelectorTerms:
             - matchExpressions:
-              - key: network.operator.openshift.io/dpu-host
+              {{ if .DpuHostModeLabel }}
+              - key: {{ .DpuHostModeLabel }}
                 {{ if eq .OVN_NODE_MODE "dpu-host" }}
+                operator: Exists
+                {{ else if eq .OVN_NODE_MODE "smart-nic" }}
+                operator: DoesNotExist
+                {{ else }}
+                operator: DoesNotExist
+                {{ end }}
+              {{ end }}
+              {{ if .SmartNicModeLabel }}
+              - key: {{ .SmartNicModeLabel }}
+                {{ if eq .OVN_NODE_MODE "dpu-host" }}
+                operator: DoesNotExist
+                {{ else if eq .OVN_NODE_MODE "smart-nic" }}
                 operator: Exists
                 {{ else }}
                 operator: DoesNotExist
                 {{ end }}
-              - key: network.operator.openshift.io/dpu
+              {{ end }}
+              {{ if .DpuModeLabel }}
+              - key: {{ .DpuModeLabel }}
                 operator: DoesNotExist
-      serviceAccountName: ovn-kubernetes-controller
+              {{ end }}
+      serviceAccountName: ovn-kubernetes-node
       hostNetwork: true
       dnsPolicy: Default
       hostPID: true
@@ -51,7 +86,7 @@ spec:
       # /run/openvswitch -> tmpfs - ovsdb sockets
       # /env -> configmap env-overrides - debug overrides
       containers:
-      {{ if eq .OVN_NODE_MODE "full" }}
+      {{ if or (eq .OVN_NODE_MODE "full") (eq .OVN_NODE_MODE "smart-nic") }}
       # ovn-controller: programs the vswitch with flows from the sbdb
       - name: ovn-controller
         image: "{{.OvnImage}}"
@@ -122,7 +157,9 @@ spec:
 
           # Rotate audit log files when then get to max size (in bytes)
           MAXFILESIZE=$(( "{{.OVNPolicyAuditMaxFileSize}}"*1000000 ))
-          LOGFILE=/var/log/ovn/acl-audit-log.log
+          MAXLOGFILES="{{.OVNPolicyAuditMaxLogFiles}}"
+          LOGDIR=/var/log/ovn
+          LOGFILE=${LOGDIR}/acl-audit-log.log
           CONTROLLERPID=$(cat /run/ovn/ovn-controller.pid)
 
           # Redirect err to null so no messages are shown upon rotation
@@ -144,6 +181,13 @@ spec:
               mv ${LOGFILE} /var/log/ovn/acl-audit-log.$timestamp.log
               ovs-appctl -t /run/ovn/ovn-controller.${CONTROLLERPID}.ctl vlog/reopen
               CONTROLLERPID=$(cat /run/ovn/ovn-controller.pid)
+            fi
+
+            # Ensure total number of log files does not exceed the maximum configured from OVNPolicyAuditMaxLogFiles
+            num_files=$(ls -1 ${LOGDIR}/acl-audit-log* 2>/dev/null | wc -l)
+            if [ "$num_files" -gt "$MAXLOGFILES" ]; then
+              num_to_delete=$(( num_files - ${MAXLOGFILES} ))
+              ls -1t ${LOGDIR}/acl-audit-log* 2>/dev/null | tail -$num_to_delete | xargs -I {} rm {}
             fi
 
             # sleep for 30 seconds to avoid wasting CPU
@@ -291,16 +335,16 @@ spec:
           echo "$(date -Iseconds) - starting ovn-northd"
           exec ovn-northd \
             --no-chdir "-vconsole:${OVN_LOG_LEVEL}" -vfile:off "-vPATTERN:console:{{.OVN_LOG_PATTERN_CONSOLE}}" \
-            --pidfile /var/run/ovn/ovn-northd.pid &
-
+            --pidfile /var/run/ovn/ovn-northd.pid \
+            --n-threads={{.NorthdThreads}} &
           wait $!
         lifecycle:
           preStop:
             exec:
               command:
-                - OVN_MANAGE_OVSDB=no
-                - /usr/share/ovn/scripts/ovn-ctl
-                - stop_northd
+                - /bin/bash
+                - -c
+                - OVN_MANAGE_OVSDB=no /usr/share/ovn/scripts/ovn-ctl stop_northd
         env:
         - name: OVN_LOG_LEVEL
           value: info
@@ -322,7 +366,7 @@ spec:
         resources:
           requests:
             cpu: 10m
-            memory: 300Mi
+            memory: 70Mi
         terminationMessagePolicy: FallbackToLogsOnError
 
       # nbdb: the northbound, or logical network object DB. In standalone mode listening on unix socket.
@@ -351,8 +395,6 @@ spec:
 
           bracketify() { case "$1" in *:*) echo "[$1]" ;; *) echo "$1" ;; esac }
 
-          # checks if a db pod is part of a current cluster
-
           OVN_ARGS="--no-monitor"
           exec /usr/share/ovn/scripts/ovn-ctl ${OVN_ARGS} \
             --ovn-nb-log="-vconsole:${OVN_LOG_LEVEL} -vfile:off -vPATTERN:console:{{.OVN_LOG_PATTERN_CONSOLE}}" \
@@ -372,6 +414,47 @@ spec:
                 #configure northd_probe_interval
                 OVN_NB_CTL="ovn-nbctl"
 
+                # retry an operation a number of times, sleeping 2 seconds between each try
+                retry() {
+                  local tries=${1}
+                  local desc=${2}
+                  local cmd=${3}
+
+                  local retries=0
+                  while ! ${cmd}; do
+                    (( retries += 1 ))
+                    if [[ "${retries}" -gt ${tries} ]]; then
+                      echo "$(date -Iseconds) - ERROR - nbdb ${desc} - too many failed attempts, giving up"
+                      return 1
+                    fi
+                    echo "$(date -Iseconds) - WARN - nbdb ${desc} - failed try ${retries}, retrying..."
+                    sleep 2
+                  done
+                  echo "$(date -Iseconds) - INFO - nbdb ${desc} - success"
+                  return 0
+                }
+
+                # set the connection and inactivity probe
+                if ! retry 60 "inactivity-probe" "ovn-nbctl --no-leader-only -t 5 set-connection pssl:{{.OVN_NB_PORT}}{{.LISTEN_DUAL_STACK}} -- set connection . inactivity_probe={{.OVN_NB_INACTIVITY_PROBE}}"; then
+                  exit 1
+                fi
+
+                # Upgrade the db if required.
+                DB_SCHEMA="/usr/share/ovn/ovn-nb.ovsschema"
+                DB_SERVER="unix:/var/run/ovn/ovnnb_db.sock"
+                schema_name=$(ovsdb-tool schema-name $DB_SCHEMA)
+                db_version=$(ovsdb-client -t 10 get-schema-version "$DB_SERVER" "$schema_name")
+                target_version=$(ovsdb-tool schema-version "$DB_SCHEMA")
+
+                if ovsdb-tool compare-versions "$db_version" == "$target_version"; then
+                  :
+                elif ovsdb-tool compare-versions "$db_version" ">" "$target_version"; then
+                    echo "Database $schema_name has newer schema version ($db_version) than our local schema ($target_version), possibly an upgrade is partially complete?"
+                else
+                    echo "Upgrading database $schema_name from schema version $db_version to $target_version"
+                    ovsdb-client -t 30 convert "$DB_SERVER" "$DB_SCHEMA"
+                fi
+
                 echo "Setting the IC zone to ${K8S_NODE}"
                 retries=0
                 current_probe_interval=0
@@ -386,7 +469,7 @@ spec:
                   fi
                 done
 
-                northd_probe_interval=${OVN_NORTHD_PROBE_INTERVAL:-5000}
+                northd_probe_interval=${OVN_NORTHD_PROBE_INTERVAL:-10000}
                 echo "Setting northd probe interval to ${northd_probe_interval} ms"
                 retries=0
                 current_probe_interval=0
@@ -406,7 +489,7 @@ spec:
                   while [[ "${retries}" -lt 10 ]]; do
                     ${OVN_NB_CTL} set NB_GLOBAL . options:northd_probe_interval=${northd_probe_interval}
                     if [[ $? != 0 ]]; then
-                      echo "Failed to set northd probe interval to ${northd_probe_interval}. retrying....."
+                      echo "Failed to set northd probe interval to ${northd_probe_interval}. retrying..."
                       sleep 2
                       (( retries += 1 ))
                     else
@@ -416,13 +499,33 @@ spec:
                   done
                 fi
 
+                # Enable/disable IPsec
+                {{ if .OVNIPsecEnable }}
+                ipsec=true
+                {{ else }}
+                ipsec=false
+                {{ end }}
+                ipsec_encapsulation=false
+                if [ "${ipsec}" == "true" ]; then
+                    # IBMCloud does not forward ESP (IP proto 50)
+                    # Instead, force IBMCloud IPsec to always use NAT-T
+                    if [ "{{.PlatformType}}" == "IBMCloud" ]; then
+                        ipsec_encapsulation=true
+                    fi
+                fi
+                if ! retry 20 "ipsec" "${OVN_NB_CTL} set nb_global . ipsec=${ipsec} options:ipsec_encapsulation=${ipsec_encapsulation}"; then
+                  exit 1
+                fi
           preStop:
             exec:
               command:
-                - /usr/bin/ovn-appctl
-                - -t
-                - /var/run/ovn/ovnnb_db.ctl
-                - exit
+                - /bin/bash
+                - -c
+                - |
+                  echo "$(date -Iseconds) - stopping nbdb"
+                  /usr/share/ovn/scripts/ovn-ctl stop_nb_ovsdb
+                  echo "$(date -Iseconds) - nbdb stopped"
+                  rm -f /var/run/ovn/ovnnb_db.pid
         readinessProbe:
 {{ if not .IsSNO }}
           initialDelaySeconds: 90
@@ -440,6 +543,8 @@ spec:
                 exit 1
               fi
 
+              # set trim-on-compaction
+              /usr/bin/ovn-appctl -t /var/run/ovn/ovnnb_db.ctl --timeout=5 ovsdb-server/memory-trim-on-compaction on 2>/dev/null
         env:
         - name: OVN_LOG_LEVEL
           value: info
@@ -472,7 +577,7 @@ spec:
             memory: 300Mi
         terminationMessagePolicy: FallbackToLogsOnError
 
-      # sbdb: the southbound, or logical network object DB. In standalone mode listening on unix socket
+      # sbdb: the southbound, or flow DB. In standalone mode listening on unix socket
       - name: sbdb
         image: "{{.OvnImage}}"
         command:
@@ -515,13 +620,61 @@ spec:
                 set -x
                 rm -f /var/run/ovn/ovnsb_db.pid
 
+                # retry an operation a number of times, sleeping 2 seconds between each try
+                retry() {
+                  local tries=${1}
+                  local desc=${2}
+                  local cmd=${3}
+
+                  local retries=0
+                  while ! ${cmd}; do
+                    (( retries += 1 ))
+                    if [[ "${retries}" -gt ${tries} ]]; then
+                      echo "$(date -Iseconds) - ERROR - sbdb ${desc} - too many failed attempts, giving up"
+                      return 1
+                    fi
+                    echo "$(date -Iseconds) - WARN - sbdb ${desc} - failed try ${retries}, retrying..."
+                    sleep 2
+                  done
+                  echo "$(date -Iseconds) - INFO - sbdb ${desc} - success"
+                  return 0
+                }
+
+                # set the connection and inactivity probe
+                if ! retry 60 "inactivity-probe" "ovn-sbctl --no-leader-only -t 5 set-connection pssl:{{.OVN_SB_PORT}}{{.LISTEN_DUAL_STACK}} -- set connection . inactivity_probe={{.OVN_CONTROLLER_INACTIVITY_PROBE}}"; then
+                  exit 1
+                fi
+
+                # Upgrade the db if required.
+                DB_SCHEMA="/usr/share/ovn/ovn-sb.ovsschema"
+                DB_SERVER="unix:/var/run/ovn/ovnsb_db.sock"
+                schema_name=$(ovsdb-tool schema-name $DB_SCHEMA)
+                db_version=$(ovsdb-client -t 10 get-schema-version "$DB_SERVER" "$schema_name")
+                target_version=$(ovsdb-tool schema-version "$DB_SCHEMA")
+                if ovsdb-tool compare-versions "$db_version" == "$target_version"; then
+                  :
+                elif ovsdb-tool compare-versions "$db_version" ">" "$target_version"; then
+                    echo "Database $schema_name has newer schema version ($db_version) than our local schema ($target_version), possibly an upgrade is partially complete?"
+                else
+                    echo "Upgrading database $schema_name from schema version $db_version to $target_version"
+                    ovsdb-client -t 30 convert "$DB_SERVER" "$DB_SCHEMA"
+                fi
+
+                # Kill some time while the cluster converges by checking IPsec status
+                OVN_SB_CTL="ovn-sbctl"
+                if ! retry 20 "ipsec" "${OVN_SB_CTL} get sb_global . ipsec"; then
+                  exit 1
+                fi
           preStop:
             exec:
               command:
-                - /usr/bin/ovn-appctl
-                - -t
-                - /var/run/ovn/ovnsb_db.ctl
-                - exit
+                - /bin/bash
+                - -c
+                - |
+                  echo "$(date -Iseconds) - stopping sbdb"
+                  /usr/share/ovn/scripts/ovn-ctl stop_sb_ovsdb
+                  echo "$(date -Iseconds) - sbdb stopped"
+                  rm -f /var/run/ovn/ovnsb_db.pid
         readinessProbe:
 {{ if not .IsSNO }}
           initialDelaySeconds: 90
@@ -538,7 +691,8 @@ spec:
                 echo "SB DB is not running or active."
                 exit 1
               fi
-
+              # set trim-on-compaction
+              /usr/bin/ovn-appctl -t /var/run/ovn/ovnsb_db.ctl --timeout=5 ovsdb-server/memory-trim-on-compaction on 2>/dev/null
         env:
         - name: OVN_LOG_LEVEL
           value: info
@@ -565,7 +719,7 @@ spec:
             memory: 300Mi
         terminationMessagePolicy: FallbackToLogsOnError
 
-      - name: kube-rbac-proxy-ncm
+      - name: kube-rbac-proxy-controller
         image: {{.KubeRBACProxyImage}}
         command:
         - /bin/bash
@@ -702,7 +856,7 @@ spec:
             fieldRef:
               fieldPath: spec.nodeName
         ports:
-        - name: metrics-port-c  # 15 characters max on windows
+        - name: metrics-port-c  # c stands for controller, we only have 15 characters max for ports on a windows platform
           containerPort: 29113
         terminationMessagePolicy: FallbackToLogsOnError
 
@@ -809,6 +963,9 @@ spec:
           if [[ -n "${OVNKUBE_NODE_MGMT_PORT_NETDEV}" ]] ; then
             node_mgmt_port_netdev_flags="--ovnkube-node-mgmt-port-netdev ${OVNKUBE_NODE_MGMT_PORT_NETDEV}"
           fi
+          if [[ -n "${OVNKUBE_NODE_MGMT_PORT_DP_RESOURCE_NAME}" ]] ; then
+            node_mgmt_port_netdev_flags="$node_mgmt_port_netdev_flags --ovnkube-node-mgmt-port-dp-resource-name ${OVNKUBE_NODE_MGMT_PORT_DP_RESOURCE_NAME}"
+          fi
 
           multi_network_enabled_flag=
           if [[ "{{.OVN_MULTI_NETWORK_ENABLE}}" == "true" ]]; then
@@ -875,6 +1032,10 @@ spec:
         - name: IPFIX_SAMPLING
           value: "{{.IPFIXSampling}}"
         {{ end }}
+        {{ if and (.MgmtPortResourceName) (or (eq .OVN_NODE_MODE "smart-nic") (eq .OVN_NODE_MODE "dpu-host")) }}
+        - name: OVNKUBE_NODE_MGMT_PORT_DP_RESOURCE_NAME
+          value: {{ .MgmtPortResourceName }}
+        {{ end }}
         - name: K8S_NODE
           valueFrom:
             fieldRef:
@@ -939,6 +1100,13 @@ spec:
           requests:
             cpu: 10m
             memory: 300Mi
+            {{ if and (.MgmtPortResourceName) (or (eq .OVN_NODE_MODE "smart-nic") (eq .OVN_NODE_MODE "dpu-host")) }}
+            {{ .MgmtPortResourceName }}: '1'
+            {{ end }}
+          {{ if and (.MgmtPortResourceName) (or (eq .OVN_NODE_MODE "smart-nic") (eq .OVN_NODE_MODE "dpu-host")) }}
+          limits:
+            {{ .MgmtPortResourceName }}: '1'
+          {{ end }}
         lifecycle:
           preStop:
             exec:
@@ -1035,14 +1203,14 @@ spec:
           path: /var/lib/openvswitch/data
       - name: etc-openvswitch
         hostPath:
-          path: /var/lib/ovn-ic/etc  # different path than 4.13 and single-zone 4.14
+          path: /var/lib/ovn-ic/etc  # different path than 4.13 and single-zone 4.14 to avoid collision during upgrade
       - name: run-openvswitch
         hostPath:
           path: /var/run/openvswitch
       - name: run-ovn
         hostPath:
-          path: /var/run/ovn-ic  # different path than 4.13 and single-zone 4.14
-      {{ if eq .OVN_NODE_MODE "full" }}
+          path: /var/run/ovn-ic  # different path than 4.13 and single-zone 4.14 to avoid collision during upgrade
+      {{ if or (eq .OVN_NODE_MODE "full") (eq .OVN_NODE_MODE "smart-nic") }}
       # Used for placement of ACL audit logs
       - name: node-log
         hostPath:
