Implement SDN live migration
Signed-off-by: Peng Liu <pliu@redhat.com>

diff --git a/bindata/network/openshift-sdn/sdn.yaml b/bindata/network/openshift-sdn/sdn.yaml
--- a/bindata/network/openshift-sdn/sdn.yaml
+++ b/bindata/network/openshift-sdn/sdn.yaml
@@ -66,7 +66,62 @@ spec:
         - |
           #!/bin/bash
           set -euo pipefail
+{{- if .IsNetworkTypeLiveMigration }}
+          # In case of rollback, openshift-sdn need to reuse the host subnet used by ovn-kube, so we need to create the hostsubnet CR for the local node if it doesn't exist.
+          # retry loop
+          RETRY_INTERVAL=3
+          MAX_RETRIES=10
+          for ((retry_count=1; retry_count<=MAX_RETRIES; retry_count++)); do
+              # Get SDN subnet
+              SDN_SUBNET=$(oc get hostsubnet ${K8S_NODE_NAME} -o jsonpath="{.subnet}"||true)
 
+              # Get OVN subnet
+              OVN_SUBNET=$(oc get node ${K8S_NODE_NAME} -o jsonpath='{.metadata.annotations.k8s\.ovn\.org/node-subnets}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/[0-9]{1,3}'||true)
+
+              if [ -n "${SDN_SUBNET}" ] && [ -z "${OVN_SUBNET}" ]; then
+                  echo "SDN_SUBNET is ${SDN_SUBNET}"
+                  break
+              elif [ -z "${SDN_SUBNET}" ] && [ -n "${OVN_SUBNET}" ]; then
+                  echo "SDN_SUBNET is empty, create the hostsubnet CR with OVN_SUBNET ${OVN_SUBNET}"
+                  SUBNET=${OVN_SUBNET}
+                  NODE_UID=$(oc get node ${K8S_NODE_NAME} -o jsonpath='{.metadata.uid}')
+                  NODE_IP=$(oc get node ${K8S_NODE_NAME} -o jsonpath='{.status.addresses[?(@.type=="InternalIP")].address}')
+          cat <<EOF | oc apply -f -
+          apiVersion: network.openshift.io/v1
+          kind: HostSubnet
+          metadata:
+            name: ${K8S_NODE_NAME}
+            annotations:
+              pod.network.openshift.io/node-uid: ${NODE_UID}
+          host: ${K8S_NODE_NAME}
+          hostIP: ${NODE_IP}
+          subnet: ${SUBNET}
+          EOF
+              elif [ -n "${SDN_SUBNET}" ] && [ -n "${OVN_SUBNET}" ] && [ "${SDN_SUBNET}" == "${OVN_SUBNET}" ]; then
+                  echo "Subnets matched! SDN_SUBNET: ${SDN_SUBNET}, OVN_SUBNET: ${OVN_SUBNET}"
+                  break
+              elif [ -n "${SDN_SUBNET}" ] && [ -n "${OVN_SUBNET}" ] && ! [ "${SDN_SUBNET}" == "${OVN_SUBNET}" ]; then
+                  echo "Subnets don't match! SDN_SUBNET: ${SDN_SUBNET}, OVN_SUBNET: ${OVN_SUBNET}"
+                  exit 1
+              else
+                  echo "Round ${retry_count}/${MAX_RETRIES} - Retrying... SDN_SUBNET: ${SDN_SUBNET}, OVN_SUBNET: ${OVN_SUBNET}"
+                  sleep $RETRY_INTERVAL
+              fi
+          done
+          if [ ${retry_count} -gt ${MAX_RETRIES} ]; then
+              echo "All retries failed. Exiting."
+              exit 1
+          fi
+          if ovs-vsctl br-exists br-ex; then
+            echo "br-ex exists, sleep..."
+            trap : TERM INT; sleep infinity & wait
+            exit
+          else
+            echo "br-ex doesn't exist"
+          fi
+          ovs-vsctl --if-exists del-br br-int
+          ovs-vsctl --if-exists del-br br-ext
+{{- end }}
           # if another process is listening on the cni-server socket, wait until it exits
           trap 'kill $(jobs -p); rm -f /etc/cni/net.d/80-openshift-network.conf ; exit 0' TERM
           retries=0
@@ -253,7 +308,18 @@ spec:
         readinessProbe:
           exec:
             # openshift-sdn writes this file when it is ready to handle pod requests.
-            command: ["test", "-f", "/etc/cni/net.d/80-openshift-network.conf"]
+            command: 
+            - /bin/bash
+            - -c
+            - |
+              #!/bin/bash
+              set -euo pipefail
+{{- if .IsNetworkTypeLiveMigration }}
+              if ovs-vsctl br-exists br-ex; then
+                exit 0
+              fi
+{{- end}}
+              test -f /etc/cni/net.d/80-openshift-network.conf
           initialDelaySeconds: 5
           periodSeconds: 5
       - name: kube-rbac-proxy
diff --git a/bindata/network/ovn-kubernetes/self-hosted/multi-zone-interconnect/ovnkube-node.yaml b/bindata/network/ovn-kubernetes/self-hosted/multi-zone-interconnect/ovnkube-node.yaml
--- a/bindata/network/ovn-kubernetes/self-hosted/multi-zone-interconnect/ovnkube-node.yaml
+++ b/bindata/network/ovn-kubernetes/self-hosted/multi-zone-interconnect/ovnkube-node.yaml
@@ -280,6 +280,12 @@ spec:
         - -c
         - |
           set -xem
+{{- if .IsNetworkTypeLiveMigration }}
+          if ! ip link show br-ex; then
+            # clean up the OVN dbs if the node is running with OpenShiftSDN
+            rm -f /etc/ovn/ovnnb_db.db /etc/ovn/ovnsb_db.db
+          fi
+{{- end }}
           if [[ -f /env/_master ]]; then
             set -o allexport
             source /env/_master
@@ -297,6 +303,11 @@ spec:
               - -c
               - |
                 set -x
+{{- if .IsNetworkTypeLiveMigration }}
+                if ! ip link show br-ex; then
+                  exit 0
+                fi
+{{- end }}
                 . /ovnkube-lib/ovnkube-lib.sh || exit 1
                 nbdb-post-start {{.OVN_NORTHD_PROBE_INTERVAL}}
         readinessProbe:
@@ -309,6 +320,11 @@ spec:
             - /bin/bash
             - -c
             - |
+{{- if .IsNetworkTypeLiveMigration }}
+              if ! ip link show br-ex; then
+                exit 0
+              fi
+{{- end }}
               set -xeo pipefail
               . /ovnkube-lib/ovnkube-lib.sh || exit 1
               ovndb-readiness-probe "nb"
@@ -361,6 +377,11 @@ spec:
               - -c
               - |
                 set -x
+{{- if .IsNetworkTypeLiveMigration }}
+                if ! ip link show br-ex; then
+                  exit 0
+                fi
+{{- end }}
                 . /ovnkube-lib/ovnkube-lib.sh || exit 1
                 sbdb-post-start
         readinessProbe:
@@ -374,6 +395,11 @@ spec:
             - -c
             - |
               set -xeo pipefail
+{{- if .IsNetworkTypeLiveMigration }}
+              if ! ip link show br-ex; then
+                exit 0
+              fi
+{{- end }}
               . /ovnkube-lib/ovnkube-lib.sh || exit 1
               ovndb-readiness-probe "sb"
         env:
@@ -404,6 +430,64 @@ spec:
         - -c
         - |
           set -xe
+{{- if .IsNetworkTypeLiveMigration }}
+          # In case of rollback, ovnkube need to reuse the host subnet used by openshift-sdn, so we need to create the node subnets annotations for the local node if it doesn't exist.
+          # retry loop
+          RETRY_INTERVAL=3
+          MAX_RETRIES=10
+          for ((retry_count=1; retry_count<=MAX_RETRIES; retry_count++)); do
+              # Get SDN subnet
+              SDN_SUBNET=$(kubectl get hostsubnet ${K8S_NODE} -o jsonpath="{.subnet}"||true)
+
+              # Get OVN subnet
+              OVN_SUBNET=$(kubectl get node ${K8S_NODE} -o jsonpath='{.metadata.annotations.k8s\.ovn\.org/node-subnets}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/[0-9]{1,3}'||true)
+
+              if [ -n "${SDN_SUBNET}" ] && [ -z "${OVN_SUBNET}" ]; then
+                  echo "OVN_SUBNET is empty, create the node-subnets annotation with the SDN_SUBNET ${SDN_SUBNET}"
+                  SUBNET=${SDN_SUBNET}
+                  break
+              elif [ -z "${SDN_SUBNET}" ] && [ -n "${OVN_SUBNET}" ]; then
+                  echo "OVN_SUBNET is ${OVN_SUBNET}"
+                  break
+              elif [ -n "${SDN_SUBNET}" ] && [ -n "${OVN_SUBNET}" ] && [ "${SDN_SUBNET}" == "${OVN_SUBNET}" ]; then
+                  echo "Subnets matched! SDN_SUBNET: ${SDN_SUBNET}, OVN_SUBNET: ${OVN_SUBNET}"
+                  SUBNET=${SDN_SUBNET}
+                  break
+              elif [ -n "${SDN_SUBNET}" ] && [ -n "${OVN_SUBNET}" ] && ! [ "${SDN_SUBNET}" == "${OVN_SUBNET}" ]; then
+                  echo "Subnets don't match! SDN_SUBNET: ${SDN_SUBNET}, OVN_SUBNET: ${OVN_SUBNET}"
+                  exit 1
+              else
+                  echo "Round ${retry_count}/${MAX_RETRIES} - Retrying... SDN_SUBNET: ${SDN_SUBNET}, OVN_SUBNET: ${OVN_SUBNET}"
+                  sleep $RETRY_INTERVAL
+              fi
+          done
+          if [ ${retry_count} -gt ${MAX_RETRIES} ]; then
+              echo "All retries failed. Exiting."
+              exit 1
+          fi
+
+          kubectl annotate node ${K8S_NODE} --overwrite k8s.ovn.org/node-subnets={\"default\":[\"${SUBNET}\"]}
+          kubectl annotate node ${K8S_NODE} --overwrite k8s.ovn.org/hybrid-overlay-node-subnet=${SUBNET}
+          if ip link show br-ex; then
+            echo "br-ex exists, run ovnkube"
+            kubectl label node --overwrite ${K8S_NODE} migration.network.openshift.io/plugin-
+          else
+            echo "br-ex doesn't exist"
+            kubectl label node --overwrite ${K8S_NODE} migration.network.openshift.io/plugin=
+            echo "run hybrid-overlay-node"
+            NETWORK_NODE_IDENTITY_ENABLE=
+            if [[ "{{.NETWORK_NODE_IDENTITY_ENABLE}}" == "true" ]]; then
+              NETWORK_NODE_IDENTITY_ENABLE="
+                --bootstrap-kubeconfig=/var/lib/kubelet/kubeconfig
+                --cert-dir=/etc/ovn/ovnkube-node-certs
+                --cert-duration={{.NodeIdentityCertDuration}}
+              "
+            fi
+            exec /usr/bin/hybrid-overlay-node --node "${K8S_NODE}" \
+              --config-file=/run/ovnkube-config/ovnkube.conf \
+              ${NETWORK_NODE_IDENTITY_ENABLE}
+          fi
+{{- end }}
           . /ovnkube-lib/ovnkube-lib.sh || exit 1
           start-ovnkube-node ${OVN_KUBE_LOG_LEVEL} 29103 29105
         env:
@@ -529,7 +613,17 @@ spec:
               command: ["rm","-f","/etc/cni/net.d/10-ovn-kubernetes.conf"]
         readinessProbe:
           exec:
-            command: ["test", "-f", "/etc/cni/net.d/10-ovn-kubernetes.conf"]
+            command:
+            - /bin/bash
+            - -c
+            - |
+              #!/bin/bash
+{{- if .IsNetworkTypeLiveMigration }}
+              if ! ip link show br-ex; then
+                exit 0
+              fi
+{{- end }}
+              test -f /etc/cni/net.d/10-ovn-kubernetes.conf
           initialDelaySeconds: 5
           periodSeconds: 30
       {{- if .OVNPlatformAzure}}
@@ -556,6 +650,15 @@ spec:
           export KUBECONFIG=/etc/ovn/kubeconfig
 {{ end }}
 
+{{- if .IsNetworkTypeLiveMigration }}
+          if ip link show br-ex; then
+            echo "br-ex exists, run"
+          else
+            echo "br-ex doesn't exist, sleep..."
+            trap : TERM INT; sleep infinity & wait
+            exit
+          fi
+{{- end }}
           touch /var/run/ovn/add_iptables.sh
           chmod 0755 /var/run/ovn/add_iptables.sh
           cat <<'EOF' > /var/run/ovn/add_iptables.sh
