ovnkube: move ovnkube container script to common library

diff --git a/bindata/network/ovn-kubernetes/common/008-script-lib.yaml b/bindata/network/ovn-kubernetes/common/008-script-lib.yaml
--- a/bindata/network/ovn-kubernetes/common/008-script-lib.yaml
+++ b/bindata/network/ovn-kubernetes/common/008-script-lib.yaml
@@ -367,3 +367,182 @@ data:
         exit 1
       fi
     }
+
+    function log()
+    {
+        echo "$(date --iso-8601=seconds) [{$1}] ${2}"
+    }
+
+    # cni-bin-copy() detects the host OS and copies the correct shim binary to
+    # the CNI binary directory.
+    #
+    # Requires the following volume mounts:
+    #   /host
+    #   /cni-bin-dir
+    cni-bin-copy()
+    {
+      # collect host os information
+      . /host/etc/os-release
+      rhelmajor=
+      # detect which version we're using in order to copy the proper binaries
+      case "${ID}" in
+        rhcos|scos)
+          RHEL_VERSION=$(echo "${CPE_NAME}" | cut -f 5 -d :)
+          rhelmajor=$(echo $RHEL_VERSION | sed -E 's/([0-9]+)\.{1}[0-9]+(\.[0-9]+)?/\1/')
+        ;;
+        rhel) rhelmajor=$(echo "${VERSION_ID}" | cut -f 1 -d .)
+        ;;
+        fedora)
+          if [ "${VARIANT_ID}" == "coreos" ]; then
+            rhelmajor=8
+          else
+            log "cnibincopy" "FATAL ERROR: Unsupported Fedora variant=${VARIANT_ID}"
+            exit 1
+          fi
+        ;;
+        *) log "cnibincopy" "FATAL ERROR: Unsupported OS ID=${ID}"; exit 1
+        ;;
+      esac
+
+      # Set which directory we'll copy from, detect if it exists
+      sourcedir=/usr/libexec/cni/
+      case "${rhelmajor}" in
+        8)
+          sourcedir=/usr/libexec/cni/rhel8
+        ;;
+        9)
+          sourcedir=/usr/libexec/cni/rhel9
+        ;;
+        *)
+          log "cnibincopy" "ERROR: RHEL Major Version Unsupported, rhelmajor=${rhelmajor}"
+        ;;
+      esac
+
+      cp -f "$sourcedir/ovn-k8s-cni-overlay" /cni-bin-dir/
+    }
+
+    # start-ovnkube-node starts the ovnkube-node process. This function does not
+    # return.
+    start-ovnkube-node()
+    {
+      local log_level=$1
+      local metrics_port=$2
+      local ovn_metrics_port=$3
+
+      # copy the right CNI shim for the host OS
+      cni-bin-copy
+
+      ovn_config_namespace=openshift-ovn-kubernetes
+      echo "I$(date "+%m%d %H:%M:%S.%N") - disable conntrack on geneve port"
+      iptables -t raw -A PREROUTING -p udp --dport {{.GenevePort}} -j NOTRACK
+      iptables -t raw -A OUTPUT -p udp --dport {{.GenevePort}} -j NOTRACK
+      ip6tables -t raw -A PREROUTING -p udp --dport {{.GenevePort}} -j NOTRACK
+      ip6tables -t raw -A OUTPUT -p udp --dport {{.GenevePort}} -j NOTRACK
+      echo "I$(date "+%m%d %H:%M:%S.%N") - starting ovnkube-node"
+
+      if [ "{{.OVN_GATEWAY_MODE}}" == "shared" ]; then
+        gateway_mode_flags="--gateway-mode shared --gateway-interface br-ex"
+      elif [ "{{.OVN_GATEWAY_MODE}}" == "local" ]; then
+        gateway_mode_flags="--gateway-mode local --gateway-interface br-ex"
+      else
+        echo "Invalid OVN_GATEWAY_MODE: \"{{.OVN_GATEWAY_MODE}}\". Must be \"local\" or \"shared\"."
+        exit 1
+      fi
+
+      export_network_flows_flags=
+      if [[ -n "${NETFLOW_COLLECTORS}" ]] ; then
+        export_network_flows_flags="--netflow-targets ${NETFLOW_COLLECTORS}"
+      fi
+      if [[ -n "${SFLOW_COLLECTORS}" ]] ; then
+        export_network_flows_flags="$export_network_flows_flags --sflow-targets ${SFLOW_COLLECTORS}"
+      fi
+      if [[ -n "${IPFIX_COLLECTORS}" ]] ; then
+        export_network_flows_flags="$export_network_flows_flags --ipfix-targets ${IPFIX_COLLECTORS}"
+      fi
+      if [[ -n "${IPFIX_CACHE_MAX_FLOWS}" ]] ; then
+        export_network_flows_flags="$export_network_flows_flags --ipfix-cache-max-flows ${IPFIX_CACHE_MAX_FLOWS}"
+      fi
+      if [[ -n "${IPFIX_CACHE_ACTIVE_TIMEOUT}" ]] ; then
+        export_network_flows_flags="$export_network_flows_flags --ipfix-cache-active-timeout ${IPFIX_CACHE_ACTIVE_TIMEOUT}"
+      fi
+      if [[ -n "${IPFIX_SAMPLING}" ]] ; then
+        export_network_flows_flags="$export_network_flows_flags --ipfix-sampling ${IPFIX_SAMPLING}"
+      fi
+      gw_interface_flag=
+      # if br-ex1 is configured on the node, we want to use it for external gateway traffic
+      if [ -d /sys/class/net/br-ex1 ]; then
+        gw_interface_flag="--exgw-interface=br-ex1"
+      fi
+
+      node_mgmt_port_netdev_flags=
+      if [[ -n "${OVNKUBE_NODE_MGMT_PORT_NETDEV}" ]] ; then
+        node_mgmt_port_netdev_flags="--ovnkube-node-mgmt-port-netdev ${OVNKUBE_NODE_MGMT_PORT_NETDEV}"
+      fi
+      if [[ -n "${OVNKUBE_NODE_MGMT_PORT_DP_RESOURCE_NAME}" ]] ; then
+        node_mgmt_port_netdev_flags="$node_mgmt_port_netdev_flags --ovnkube-node-mgmt-port-dp-resource-name ${OVNKUBE_NODE_MGMT_PORT_DP_RESOURCE_NAME}"
+      fi
+
+      multi_network_enabled_flag=
+      if [[ "{{.OVN_MULTI_NETWORK_ENABLE}}" == "true" ]]; then
+        multi_network_enabled_flag="--enable-multi-network"
+      fi
+
+      multi_network_policy_enabled_flag=
+      if [[ "{{.OVN_MULTI_NETWORK_POLICY_ENABLE}}" == "true" ]]; then
+        multi_network_policy_enabled_flag="--enable-multi-networkpolicy"
+      fi
+
+      admin_network_policy_enabled_flag=
+      if [[ "{{.OVN_ADMIN_NETWORK_POLICY_ENABLE}}" == "true" ]]; then
+        admin_network_policy_enabled_flag="--enable-admin-network-policy"
+      fi
+
+      # If IP Forwarding mode is global set it in the host here.
+      ip_forwarding_flag=
+      if [ "{{.IP_FORWARDING_MODE}}" == "Global" ]; then
+        sysctl -w net.ipv4.ip_forward=1
+        sysctl -w net.ipv6.conf.all.forwarding=1
+      else
+        ip_forwarding_flag="--disable-forwarding"
+      fi
+
+      NETWORK_NODE_IDENTITY_ENABLE=
+      if [[ "{{.NETWORK_NODE_IDENTITY_ENABLE}}" == "true" ]]; then
+        NETWORK_NODE_IDENTITY_ENABLE="
+          --bootstrap-kubeconfig=/var/lib/kubelet/kubeconfig
+          --cert-dir=/etc/ovn/ovnkube-node-certs
+          --cert-duration={{.NodeIdentityCertDuration}}
+        "
+      fi
+
+      exec /usr/bin/ovnkube \
+        --init-ovnkube-controller "${K8S_NODE}" \
+        --init-node "${K8S_NODE}" \
+        --config-file=/run/ovnkube-config/ovnkube.conf \
+        --ovn-empty-lb-events \
+        --loglevel "${log_level}" \
+        --inactivity-probe="${OVN_CONTROLLER_INACTIVITY_PROBE}" \
+        ${gateway_mode_flags} \
+        ${node_mgmt_port_netdev_flags} \
+{{- if eq .OVN_NODE_MODE "dpu-host" }}
+        --ovnkube-node-mode dpu-host \
+{{- end }}
+        --metrics-bind-address "127.0.0.1:${metrics_port}" \
+        --ovn-metrics-bind-address "127.0.0.1:${ovn_metrics_port}" \
+        --metrics-enable-pprof \
+        --metrics-enable-config-duration \
+        --export-ovs-metrics \
+        --disable-snat-multiple-gws \
+        ${export_network_flows_flags} \
+        ${multi_network_enabled_flag} \
+        ${multi_network_policy_enabled_flag} \
+        ${admin_network_policy_enabled_flag} \
+        --enable-multicast \
+        --zone ${K8S_NODE} \
+        --enable-interconnect \
+        --acl-logging-rate-limit "{{.OVNPolicyAuditRateLimit}}" \
+        ${gw_interface_flag} \
+        --enable-multi-external-gateway=true \
+        ${ip_forwarding_flag} \
+        ${NETWORK_NODE_IDENTITY_ENABLE}
+    }
