Cleanup ipsec entries from sidecar container
The previous commit deletes ipsec entries in the preStop of the ovn-ipsec
container just before killing ovs-monitor-ipsec script. We never know
it may cause any other potential issues when cleanup and ovs-monitor-ipsec
running at the same time. hence moving ipsec cleanup logic into the sidecar
container so that it happens only after ovs-monitor-ipsec is killed.

Signed-off-by: Periyasamy Palanisamy <pepalani@redhat.com>
(cherry picked from commit e58b5610343b7db5b6006bf38d2c322f91cbacd1)

diff --git a/bindata/network/ovn-kubernetes/common/ipsec-host.yaml b/bindata/network/ovn-kubernetes/common/ipsec-host.yaml
--- a/bindata/network/ovn-kubernetes/common/ipsec-host.yaml
+++ b/bindata/network/ovn-kubernetes/common/ipsec-host.yaml
@@ -285,68 +285,8 @@ spec:
                  - |
                    #!/bin/bash
                    set -exuo pipefail
-
-{{ if .NETWORK_NODE_IDENTITY_ENABLE }}
-                   # When NETWORK_NODE_IDENTITY_ENABLE is true, use the per-node certificate to create a kubeconfig
-                   # that will be used to talk to the API
-
-
-                   # Wait for cert file
-                   retries=0
-                   tries=20
-                   key_cert="/etc/ovn/ovnkube-node-certs/ovnkube-client-current.pem"
-                   while [ ! -f "${key_cert}" ]; do
-                     (( retries += 1 ))
-                     if [[ "${retries}" -gt ${tries} ]]; then
-                       echo "$(date -Iseconds) - ERROR - ${key_cert} not found"
-                       return 1
-                     fi
-                     sleep 1
-                   done
-
-                   cat << EOF > /var/run/ovnkube-kubeconfig
-                   apiVersion: v1
-                   clusters:
-                     - cluster:
-                         certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
-                         server: {{.K8S_APISERVER}}
-                       name: default-cluster
-                   contexts:
-                     - context:
-                         cluster: default-cluster
-                         namespace: default
-                         user: default-auth
-                       name: default-context
-                   current-context: default-context
-                   kind: Config
-                   preferences: {}
-                   users:
-                     - name: default-auth
-                       user:
-                         client-certificate: /etc/ovn/ovnkube-node-certs/ovnkube-client-current.pem
-                         client-key: /etc/ovn/ovnkube-node-certs/ovnkube-client-current.pem
-                   EOF
-                   export KUBECONFIG=/var/run/ovnkube-kubeconfig
-{{ end }}
-                   # It is safe to flush xfrm states and policies and delete openshift.conf
-                   # file when east-west ipsec is disabled. This fixes a race condition when
-                   # ovs-monitor-ipsec is not fast enough to notice ipsec config change and
-                   # delete entries before it's being killed.
-                   # Since it's cleaning up all xfrm states and policies, it may cause slight
-                   # interruption until ipsec is restarted in case of external ipsec config.
-                   # We must do this before killing ovs-monitor-ipsec script, otherwise
-                   # preStop hook doesn't get a chance to run it because ovn-ipsec container
-                   # is abruptly terminated.
-                   # When east-west ipsec is not disabled, then do not flush xfrm states and
-                   # policies in order to maintain traffic flows during container restart.
-                   if [ "$(kubectl get networks.operator.openshift.io cluster -ojsonpath='{.spec.defaultNetwork.ovnKubernetesConfig.ipsecConfig.mode}')" != "Full" ] || \
-                      [ "$(kubectl get networks.operator.openshift.io cluster -ojsonpath='{.spec.defaultNetwork.ovnKubernetesConfig.ipsecConfig}')" != "{}" ]; then
-                     ip x s flush
-                     ip x p flush
-                     rm -f /etc/ipsec.d/openshift.conf
-                     # since pluto is on the host, we need to restart it after the flush
-                     chroot /proc/1/root ipsec restart
-                   fi
+                   # In order to maintain traffic flows during container restart, we
+                   # need to ensure that xfrm state and policies are not flushed.
 
                    # Don't allow ovs monitor to cleanup persistent state
                    kill "$(cat /var/run/openvswitch/ovs-monitor-ipsec.pid 2>/dev/null)" 2>/dev/null || true
@@ -358,10 +298,6 @@ spec:
         securityContext:
           privileged: true
         volumeMounts:
-{{ if .NETWORK_NODE_IDENTITY_ENABLE }}
-        - mountPath: /etc/ovn/
-          name: etc-ovn
-{{ end }}
         # To check that network setup is complete
         - mountPath: /etc/cni/net.d
           name: host-cni-netd
@@ -397,6 +333,141 @@ spec:
               fi
           initialDelaySeconds: 15
           periodSeconds: 60
+      - name: ovn-ipsec-cleanup
+        image: "{{.OvnImage}}"
+        command:
+        - /bin/bash
+        - -c
+        - |
+          #!/bin/bash
+{{ if .NETWORK_NODE_IDENTITY_ENABLE }}
+          # When NETWORK_NODE_IDENTITY_ENABLE is true, use the per-node certificate to create a kubeconfig
+          # that will be used to talk to the API
+
+
+          # Wait for cert file
+          retries=0
+          tries=20
+          key_cert="/etc/ovn/ovnkube-node-certs/ovnkube-client-current.pem"
+          while [ ! -f "${key_cert}" ]; do
+            (( retries += 1 ))
+            if [[ "${retries}" -gt ${tries} ]]; then
+              echo "$(date -Iseconds) - ERROR - ${key_cert} not found"
+              return 1
+            fi
+            sleep 1
+          done
+
+          cat << EOF > /var/run/ovnkube-kubeconfig
+          apiVersion: v1
+          clusters:
+            - cluster:
+                certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
+                server: {{.K8S_APISERVER}}
+              name: default-cluster
+          contexts:
+            - context:
+                cluster: default-cluster
+                namespace: default
+                user: default-auth
+              name: default-context
+          current-context: default-context
+          kind: Config
+          preferences: {}
+          users:
+            - name: default-auth
+              user:
+                client-certificate: /etc/ovn/ovnkube-node-certs/ovnkube-client-current.pem
+                client-key: /etc/ovn/ovnkube-node-certs/ovnkube-client-current.pem
+          EOF
+          export KUBECONFIG=/var/run/ovnkube-kubeconfig
+{{ end }}
+
+          # It is safe to flush xfrm states and policies and delete openshift.conf
+          # file when east-west ipsec is disabled. This fixes a race condition when
+          # ovs-monitor-ipsec is not fast enough to notice ipsec config change and
+          # delete entries before it's being killed.
+          # Since it's cleaning up all xfrm states and policies, it may cause slight
+          # interruption until ipsec is restarted in case of external ipsec config.
+          # We must do this before killing ovs-monitor-ipsec script, otherwise
+          # preStop hook doesn't get a chance to run it because ovn-ipsec container
+          # is abruptly terminated.
+          # When east-west ipsec is not disabled, then do not flush xfrm states and
+          # policies in order to maintain traffic flows during container restart.
+          ipsecflush() {
+            if [ "$(kubectl get networks.operator.openshift.io cluster -ojsonpath='{.spec.defaultNetwork.ovnKubernetesConfig.ipsecConfig.mode}')" != "Full" ] || \
+               [ "$(kubectl get networks.operator.openshift.io cluster -ojsonpath='{.spec.defaultNetwork.ovnKubernetesConfig.ipsecConfig}')" != "{}" ]; then
+              ip x s flush
+              ip x p flush
+              rm -f /etc/ipsec.d/openshift.conf
+              # since pluto is on the host, we need to restart it after the flush
+              chroot /proc/1/root ipsec restart
+            fi
+          }
+
+          # Function to handle SIGTERM
+          cleanup() {
+            echo "received SIGTERM, flushing ipsec config"
+            # Wait upto 15 seconds for ovs-monitor-ipsec process to terminate before
+            # cleaning up ipsec entries.
+            counter=0
+            while kill -0 "$(cat /var/run/openvswitch/ovs-monitor-ipsec.pid 2>/dev/null)"; do
+              counter=$((counter+1))
+              sleep 1
+              if [ $counter -gt 15 ];
+              then
+                echo "ovs-monitor-ipsec has not terminated after $counter seconds"
+                break
+              fi
+            done
+            ipsecflush
+            exit 0
+          }
+
+          # Trap SIGTERM and call cleanup function
+          trap cleanup SIGTERM
+
+          counter=0
+          until [ -r /var/run/openvswitch/ovs-monitor-ipsec.pid ]; do
+            counter=$((counter+1))
+            sleep 1
+            if [ $counter -gt 300 ];
+            then
+              echo "ovs-monitor-ipsec has not started after $counter seconds"
+              exit 1
+            fi
+          done
+          echo "ovs-monitor-ipsec is started"
+
+          # Monitor the ovs-monitor-ipsec process.
+          while kill -0 "$(cat /var/run/openvswitch/ovs-monitor-ipsec.pid 2>/dev/null)"; do
+            sleep 1
+          done
+
+          # Once the ovs-monitor-ipsec process terminates, execute the cleanup command.
+          echo "ovs-monitor-ipsec is terminated, flushing ipsec config"
+          ipsecflush
+
+          # Continue running until SIGTERM is received (or exit naturally)
+          while true; do
+            sleep 1
+          done
+        securityContext:
+          privileged: true
+        volumeMounts:
+{{ if .NETWORK_NODE_IDENTITY_ENABLE }}
+        - mountPath: /etc/ovn/
+          name: etc-ovn
+{{ end }}
+        - mountPath: /var/run
+          name: host-var-run
+        - mountPath: /etc
+          name: host-etc
+        resources:
+          requests:
+            cpu: 10m
+            memory: 50Mi
+        terminationMessagePolicy: FallbackToLogsOnError
       nodeSelector:
         kubernetes.io/os: "linux"
       terminationGracePeriodSeconds: 10
