Add ike healing for IPsec SAs
ref: https://gist.github.com/trozet/4900e476394db09e9f09abc467c9f771

Signed-off-by: Periyasamy Palanisamy <pepalani@redhat.com>

diff --git a/bindata/network/ovn-kubernetes/common/ipsec-host.yaml b/bindata/network/ovn-kubernetes/common/ipsec-host.yaml
--- a/bindata/network/ovn-kubernetes/common/ipsec-host.yaml
+++ b/bindata/network/ovn-kubernetes/common/ipsec-host.yaml
@@ -207,6 +207,97 @@ spec:
             memory: 100Mi
         terminationMessagePolicy: FallbackToLogsOnError
       containers:
+      - command:
+        - /bin/bash
+        - -c
+        - |
+          #!/bin/bash
+          set -exuo pipefail
+
+{{ if .IPsecCheckForLibreswan }}
+          if ! rpm --dbpath=/usr/share/rpm -q libreswan; then
+            echo "host doesnt have libreswan, therefore ipsec will be configured by ipsec-containerized daemonset, this ovn ipsec container will sleep to infinity"
+            sleep infinity
+          fi
+{{ end }}
+
+          sleep 15m
+          echo "Running IKE heal loop..."
+          # Path to the ipsec configuration file and control socket
+          IPSEC_CONF="/etc/ipsec.d/openshift.conf"
+          PLUTO_CTL="/var/run/pluto/pluto.ctl"
+          # Function to get active connections from Libreswan (pluto)
+          get_active_connections() {
+              # Get the list of active IKE connections
+              ipsec status | grep ESTABLISHED_IKE| grep -Eo 'ovn-[-A-Za-z0-9]+' | sed -E 's/-(in|out)-[0-9]+$//'
+          }
+          # Function to get defined connections from ipsec.conf
+          get_defined_connections() {
+             # Extract connection names from ipsec.conf
+             grep '^conn ovn-' "$IPSEC_CONF" | awk '{print $2}' | sort
+          }
+          # Function to replace the connection
+          replace_connection() {
+             local conn_name="$1"
+             echo "$(date): Replacing missing connection: $conn_name"
+             ipsec auto --config "$IPSEC_CONF" --ctlsocket "$PLUTO_CTL" --replace "$conn_name"
+          }
+          heal_ike() {
+             # Get the lists of active and defined connections
+             active_connections=$(get_active_connections)
+             defined_connections=$(get_defined_connections)
+             # Compare defined connections with active ones
+             for conn in $defined_connections; do
+                 parsed_conn=$(echo $conn | sed -E 's/-(in|out)-[0-9]+$//')
+                 if ! echo "$active_connections" | grep -q "$parsed_conn"; then
+                     already_parsed=0
+                     for item in "${replaced_parsed_conns[@]}"; do
+                         if [[ "$item" == "$parsed_conn" ]]; then
+                             already_parsed=1
+                             break
+                         fi
+                     done
+                    if [[ $already_parsed -eq 0 ]]; then
+                        # Connection is missing, so replace it
+                        replaced_parsed_conns+=("$parsed_conn")
+                        replace_connection "$conn"
+                    fi
+                 fi
+                 ipsec auto --config "$IPSEC_CONF" --ctlsocket "$PLUTO_CTL" --up "$conn"
+             done
+          }
+          # Main loop
+          while true; do
+              heal_ike
+              sleep 30
+          done
+        image: "{{.OvnImage}}"
+        imagePullPolicy: IfNotPresent
+        name: heal-ike
+        resources:
+          requests:
+            cpu: 10m
+            memory: 100Mi
+        securityContext:
+          privileged: true
+        terminationMessagePath: /dev/termination-log
+        terminationMessagePolicy: FallbackToLogsOnError
+        volumeMounts:
+        - mountPath: /etc/cni/net.d
+          name: host-cni-netd
+        - mountPath: /var/run
+          name: host-var-run
+        - mountPath: /var/log/openvswitch/
+          name: host-var-log-ovs
+        - mountPath: /etc/openvswitch
+          name: etc-openvswitch
+        - mountPath: /var/lib
+          name: host-var-lib
+        - mountPath: /etc
+          name: host-etc
+        - mountPath: /usr/share/rpm
+          name: host-usr-share-rpm
+          readOnly: true
       # ovs-monitor-ipsec and libreswan daemons
       - name: ovn-ipsec
         image: "{{.OvnImage}}"
