ipsec: move pluto to host
this is done to allow co-existance with host configured ipsec tunnels

To avoid mounting the whole host fs, only the configuration files are shared. including NSS DB and the whole ipsec configuration

hostPID is used, so that the pid file make sense from the host as well. that required moving the termination logic to a preStop lifecycle step.

the rest stays pretty much the same :-)

diff --git a/bindata/network/ovn-kubernetes/common/ipsec.yaml b/bindata/network/ovn-kubernetes/common/ipsec.yaml
--- a/bindata/network/ovn-kubernetes/common/ipsec.yaml
+++ b/bindata/network/ovn-kubernetes/common/ipsec.yaml
@@ -35,6 +35,7 @@ spec:
               - key: network.operator.openshift.io/dpu-host
                 operator: DoesNotExist
       serviceAccountName: ovn-kubernetes-node
+      hostPID: true
       hostNetwork: true
       dnsPolicy: Default
       priorityClassName: "system-node-critical"
@@ -142,12 +143,14 @@ spec:
         securityContext:
           privileged: true
         volumeMounts:
-        - mountPath: /var/run/openvswitch
-          name: host-var-run-ovs
+        - mountPath: /var/run
+          name: host-var-run
         - mountPath: /signer-ca
           name: signer-ca
         - mountPath: /etc/openvswitch
           name: etc-openvswitch
+        - mountPath: /etc
+          name: host-etc
         - mountPath: /usr/share/rpm
           name: host-usr-share-rpm
           readOnly: true
@@ -167,20 +170,6 @@ spec:
           #!/bin/bash
           set -exuo pipefail
 
-          function cleanup()
-          {
-            # In order to maintain traffic flows during container restart, we
-            # need to ensure that xfrm state and policies are not flushed.
-
-            # Don't allow ovs monitor to cleanup persistent state
-            kill $(cat /var/run/openvswitch/ovs-monitor-ipsec.pid 2>/dev/null) 2>/dev/null || true
-            # Don't allow pluto to clear xfrm state and policies on exit
-            kill -9 $(cat /var/run/pluto/pluto.pid 2>/devnull) 2>/dev/null || true
-
-            /usr/sbin/ipsec --stopnflog
-            exit 0
-          }
-          trap cleanup SIGTERM
 
           if ! rpm --dbpath=/usr/share/rpm -q libreswan; then
             echo "no libreswan on host, ovn-ipsec will sleep infinity"
@@ -226,6 +215,26 @@ spec:
             --pidfile=/var/run/openvswitch/ovs-monitor-ipsec.pid --ike-daemon=libreswan --no-restart-ike-daemon \
             --ipsec-d /var/lib/ipsec/nss \
             --log-file --monitor unix:/var/run/openvswitch/db.sock
+        lifecycle:
+           preStop:
+             exec:
+               command:
+                 - /bin/bash
+                 - -c
+                 - |
+                   #!/bin/bash
+                   set -exuo pipefail
+                   # In order to maintain traffic flows during container restart, we
+                   # need to ensure that xfrm state and policies are not flushed.
+
+                   # Don't allow ovs monitor to cleanup persistent state
+                   kill $(cat /var/run/openvswitch/ovs-monitor-ipsec.pid 2>/dev/null) 2>/dev/null || true
+                   # Don't allow pluto to clear xfrm state and policies on exit
+                   kill -9 $(cat /var/run/pluto/pluto.pid 2>/devnull) 2>/dev/null || true
+                   rm /var/run/pluto/pluto.pid
+                   rm /var/run/pluto/pluto.ctl
+
+                   /usr/sbin/ipsec --stopnflog
         env:
         - name: K8S_NODE
           valueFrom:
@@ -237,12 +246,16 @@ spec:
         # To check that network setup is complete
         - mountPath: /etc/cni/net.d
           name: host-cni-netd
-        - mountPath: /var/run/openvswitch
-          name: host-var-run-ovs
+        - mountPath: /var/run
+          name: host-var-run
         - mountPath: /var/log/openvswitch/
           name: host-var-log-ovs
         - mountPath: /etc/openvswitch
           name: etc-openvswitch
+        - mountPath: /var/lib
+          name: host-var-lib
+        - mountPath: /etc
+          name: host-etc
         - mountPath: /usr/share/rpm
           name: host-usr-share-rpm
           readOnly: true
@@ -270,28 +283,38 @@ spec:
         beta.kubernetes.io/os: "linux"
       terminationGracePeriodSeconds: 10
       volumes:
-      - name: host-var-log-ovs
-        hostPath:
+      - hostPath:
           path: /var/log/openvswitch
           type: DirectoryOrCreate
-      - name: host-var-run-ovs
-        hostPath:
-          path: /var/run/openvswitch
-          type: DirectoryOrCreate
-      - name: signer-ca
-        configMap:
+        name: host-var-log-ovs
+      - configMap:
+          defaultMode: 420
           name: signer-ca
-      - name: etc-openvswitch
-        hostPath:
+        name: signer-ca
+      - hostPath:
           path: /var/lib/openvswitch/etc
           type: DirectoryOrCreate
-      - name: host-cni-netd
-        hostPath:
-          path: "{{.CNIConfDir}}"
+        name: etc-openvswitch
+      - hostPath:
+          path: /var/run/multus/cni/net.d
+          type: ""
+        name: host-cni-netd
+      - hostPath:
+          path: /var/run
+          type: DirectoryOrCreate
+        name: host-var-run
+      - hostPath:
+          path: /var/lib
+          type: DirectoryOrCreate
+        name: host-var-lib
+      - hostPath:
+          path: /etc
+          type: Directory
+        name: host-etc
       - name: host-usr-share-rpm
         hostPath:
           path: /usr/share/rpm
-          type: Directory
+          type: DirectoryOrCreate
       tolerations:
       - operator: "Exists"
 {{end}}
