Full OVN interconnect support for self-hosted and managed
Enable OVN interconnect for self-hosted and managed. By default, the cluster is in multizone: every node is in its own zone. In order to allow upgrades from 4.13, which has no interconnect support, single-zone mode is necessary as an intermediate step: we first upgrade to 4.14 single zone, which keeps the an equivalent architecture as in 4.13, but is interconnect aware; only then we switch to multizone.

The rationale is that before we can have multizone, we need the whole cluster to enable interconnect first, in our case with single zone to match the existing architecture, because otherwise when we start applying multizone and we take away nodes from the global zones and mark them as belonging to their own zone, the rest of the cluster wouldn't be able to talk to them if it's not IC-enabled.

CNO pushes a configmap during upgrades from 4.13 in order to keep track of the intermediate (and temporary) step with single-zone mode. The same configmap can also be used to switch from single zone to multizone and back, for internal use only.

The YAMLs for each zone mode (single zone, multi zone) are to be found in separate folders, for both self-hosted and managed.

Avoid clashes between single-zone ovnkube-master (using ports 9102, 9641, 9642, 29102) and multizone ovnkube-node (initially using ports 9103, 9105, 9102, 29102, 29103) during upgrade from 4.13 and avoid using ports reserved for the storage components, as described in https://github.com/openshift/enhancements/blob/master/dev-guide/host-port-registry.md  This caused the storage operator to never be available after installation of or upgrade to 4.14.

In multizone ovnkube-node let's now have:
- 9103, 9105, 29103 (which don't collide with single-zone ovnkube-master)
- 9112, 9112 9113, 29113 so as to not collide with single-zone ovnkube-master

CNO version is not updated until 2-phase upgrade is over. In the very last step of the 2-phase upgrade to OVN interconnect, we remove the IC configmap.
At this point, SetFromPods from pod_status.go won't be called any more, because all changes to the daemonsets have been processed. Patch the ovnk master daemonset with a dummy annotation to trigger status recalculation.

Signed-off-by: Riccardo Ravaioli <rravaiol@redhat.com>

diff --git a/bindata/network/ovn-kubernetes/managed/single-zone-interconnect/ovnkube-node.yaml b/bindata/network/ovn-kubernetes/managed/single-zone-interconnect/ovnkube-node.yaml
--- a/bindata/network/ovn-kubernetes/managed/single-zone-interconnect/ovnkube-node.yaml
+++ b/bindata/network/ovn-kubernetes/managed/single-zone-interconnect/ovnkube-node.yaml
@@ -79,6 +79,64 @@ spec:
       dnsPolicy: Default
       hostPID: true
       priorityClassName: "system-node-critical"
+      # When proxy is enabled in hypershift, ovn sbdb requests are redirected
+      # to 127.0.0.1 with hostAlias settings. Ovnkube-node-proxy container
+      # listens on 127.0.0.1 and connects to destination ovn sbdb route or
+      # node port service through http proxy server.
+      {{if .ENABLE_OVN_NODE_PROXY}}
+      hostAliases:
+      - hostnames:
+        - {{.OVN_SB_DB_ROUTE_HOST}}
+        ip: 127.0.0.1
+      {{end}}
+      initContainers:
+      # ovnkube-node-init: wait for sbdb ready
+      {{ if or (eq .OVN_NODE_MODE "full") (eq .OVN_NODE_MODE "smart-nic") }}
+      - name: ovnkube-node-init
+        image: "{{.OvnImage}}"
+        command:
+        - /bin/bash
+        - -c
+        - |
+          set -xe
+          if [[ -f "/env/${K8S_NODE}" ]]; then
+            set -o allexport
+            source "/env/${K8S_NODE}"
+            set +o allexport
+          fi
+          echo "$(date -Iseconds) - checking sbdb"
+
+          {{if .ENABLE_OVN_NODE_PROXY}}
+          # Don't use /etc/hosts to resolve OVN_SB_DB_ROUTE_HOST which points to 127.0.0.1 (see spec.hostAliases)
+          echo "hosts: dns files" >> /etc/nsswitch.conf
+          exec socat TCP-LISTEN:{{.OVN_SB_DB_ROUTE_LOCAL_PORT}},reuseaddr,fork PROXY:{{.HTTP_PROXY_IP}}:{{.OVN_SB_DB_ROUTE_HOST}}:{{.OVN_SB_DB_ROUTE_PORT}},proxyport={{.HTTP_PROXY_PORT}} &
+          proxypid=$!
+         {{end}}
+
+          ovndb_ctl_ssl_opts="-p /ovn-cert/tls.key -c /ovn-cert/tls.crt -C /ovn-ca/ca-bundle.crt"
+          sbdb_ip="{{.OVN_SB_DB_ENDPOINT}}"
+          retries=0
+          while ! ovn-sbctl --no-leader-only --timeout=5 --db=${sbdb_ip} ${ovndb_ctl_ssl_opts} get-connection; do
+            (( retries += 1 ))
+            if [[ "${retries}" -gt 40 ]]; then
+              echo "$(date -Iseconds) - ERROR RESTARTING - sbdb - too many failed ovn-sbctl attempts, giving up"
+              exit 1
+            fi
+            sleep 2
+          done
+
+          {{if .ENABLE_OVN_NODE_PROXY}}
+          kill $proxypid
+          {{end}}
+        volumeMounts:
+        - mountPath: /env
+          name: env-overrides
+        - mountPath: /ovn-cert
+          name: ovn-cert
+        - mountPath: /ovn-ca
+          name: ovn-ca
+      {{ end }}
+
       # volumes in all containers:
       # (container) -> (host)
       # /etc/openvswitch -> /etc/openvswitch - ovsdb system id
@@ -87,6 +145,38 @@ spec:
       # /env -> configmap env-overrides - debug overrides
       containers:
       {{ if or (eq .OVN_NODE_MODE "full") (eq .OVN_NODE_MODE "smart-nic") }}
+      {{if .ENABLE_OVN_NODE_PROXY}}
+      # ovnkube-node-proxy redirects ovn sbdb traffic to http proxy
+      - name: ovnkube-node-proxy
+        image: "{{.OvnImage}}"
+        command:
+        - /bin/bash
+        - -c
+        - |
+          set -xe
+          if [[ -f "/env/${K8S_NODE}" ]]; then
+            set -o allexport
+            source "/env/${K8S_NODE}"
+            set +o allexport
+          fi
+          echo "$(date -Iseconds) - starting ovnkube-node-proxy"
+          # Don't use /etc/hosts to resolve OVN_SB_DB_ROUTE_HOST which points to 127.0.0.1 (see spec.hostAliases)
+          echo "hosts: dns files" >> /etc/nsswitch.conf
+          exec socat TCP-LISTEN:{{.OVN_SB_DB_ROUTE_LOCAL_PORT}},reuseaddr,fork PROXY:{{.HTTP_PROXY_IP}}:{{.OVN_SB_DB_ROUTE_HOST}}:{{.OVN_SB_DB_ROUTE_PORT}},proxyport={{.HTTP_PROXY_PORT}}
+        env:
+        - name: K8S_NODE
+          valueFrom:
+            fieldRef:
+              fieldPath: spec.nodeName
+        volumeMounts:
+        - mountPath: /env
+          name: env-overrides
+        terminationMessagePolicy: FallbackToLogsOnError
+        resources:
+          requests:
+            cpu: 10m
+            memory: 20Mi
+      {{end}}
       # ovn-controller: programs the vswitch with flows from the sbdb
       - name: ovn-controller
         image: "{{.OvnImage}}"
@@ -312,6 +402,7 @@ spec:
             source "/env/${K8S_NODE}"
             set +o allexport
           fi
+          echo "I$(date "+%m%d %H:%M:%S.%N") - waiting for db_ip addresses"
           cp -f /usr/libexec/cni/ovn-k8s-cni-overlay /cni-bin-dir/
           ovn_config_namespace=openshift-ovn-kubernetes
           echo "I$(date "+%m%d %H:%M:%S.%N") - disable conntrack on geneve port"
@@ -319,7 +410,9 @@ spec:
           iptables -t raw -A OUTPUT -p udp --dport {{.GenevePort}} -j NOTRACK
           ip6tables -t raw -A PREROUTING -p udp --dport {{.GenevePort}} -j NOTRACK
           ip6tables -t raw -A OUTPUT -p udp --dport {{.GenevePort}} -j NOTRACK
-          echo "I$(date "+%m%d %H:%M:%S.%N") - starting ovnkube-node"
+          retries=0
+
+          echo "I$(date "+%m%d %H:%M:%S.%N") - starting ovnkube-node db_ip ${db_ip}"
 
           if [ "{{.OVN_GATEWAY_MODE}}" == "shared" ]; then
             gateway_mode_flags="--gateway-mode shared --gateway-interface br-ex"
@@ -367,15 +460,17 @@ spec:
           if [[ "{{.OVN_MULTI_NETWORK_ENABLE}}" == "true" ]]; then
             multi_network_enabled_flag="--enable-multi-network"
           fi
-
+          
           multi_network_policy_enabled_flag=
           if [[ "{{.OVN_MULTI_NETWORK_POLICY_ENABLE}}" == "true" ]]; then
             multi_network_policy_enabled_flag="--enable-multi-networkpolicy"
           fi
 
           exec /usr/bin/ovnkube --init-node "${K8S_NODE}" \
-            --nb-address "{{.OVN_NB_DB_LIST}}" \
-            --sb-address "{{.OVN_SB_DB_LIST}}" \
+            --enable-interconnect \
+            --zone global \
+            --nb-address "{{.OVN_NB_DB_ENDPOINT}}" \
+            --sb-address "{{.OVN_SB_DB_ENDPOINT}}" \
             --nb-client-privkey /ovn-cert/tls.key \
             --nb-client-cert /ovn-cert/tls.crt \
             --nb-client-cacert /ovn-ca/ca-bundle.crt \
@@ -411,6 +506,18 @@ spec:
           value: "{{.OVN_CONTROLLER_INACTIVITY_PROBE}}"
         - name: OVN_KUBE_LOG_LEVEL
           value: "4"
+{{ if .HTTP_PROXY }}
+        - name: "HTTP_PROXY"
+          value: "{{ .HTTP_PROXY}}"
+{{ end }}
+{{ if .HTTPS_PROXY }}
+        - name: "HTTPS_PROXY"
+          value: "{{ .HTTPS_PROXY}}"
+{{ end }}
+{{ if .NO_PROXY }}
+        - name: "NO_PROXY"
+          value: "{{ .NO_PROXY}}"
+{{ end }}
         {{ if .NetFlowCollectors }}
         - name: NETFLOW_COLLECTORS
           value: "{{.NetFlowCollectors}}"
